
import javax.swing.table.DefaultTableModel;
import java.util.StringTokenizer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kenph
 */
public class NewJFrame extends javax.swing.JFrame {
    //int [] nums  = {7,2,4,8,3,9,1,5,10,6};
    /**
     * Creates new form NewJFrame
     */
   private int numsArray[];
    public NewJFrame() {
        initComponents();
        
        /*DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("1");
        model.addColumn("2");
        model.addColumn("3");
        model.addColumn("4");
        model.addColumn("5");
        model.addColumn("6");
        model.addColumn("7");
        model.addColumn("8");
        model.addColumn("9");
        model.addColumn("10");
        
        model.addRow(new Object[]{nums});
        
        myTable.setModel(model);
        */
    }
  
    //int [] numArreglo = new int [10];
    //String arregloNumeros; 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resul = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        numeroBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        numArreglo0 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese 10 numeros");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero a buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(numArreglo0, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resul, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jButton1))
                            .addComponent(numeroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(numArreglo0, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numeroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(resul, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*int [] nums = new int [10];
        nums[0]=2;
        nums[1]=5;
        nums[2]=6;
        nums[3]=8;
        nums[4]=10;
        nums[5]=12;
        nums[6]=1;
        nums[7]=10;
        nums[8]=14;
        nums[9]=20;
        */
        
        int numsArray[] = valArray(numArreglo0.getText());
        //int [] nums  = {7,2,4,8,3,9,1,5,10,6};
        int pos = -1;
        
        int cantIntercambios = 0; //Función qué cuenta la cantidad de intercambios
        //bucle anidado donde compara los numeros
        for (boolean ordenado=false;!ordenado;){ //
            for (int i=0;i<numsArray.length-1;i++){
                if (numsArray[i]>numsArray[i+1]){
                    //Los valores cambian de posición
                    int variableauxiliar=numsArray[i];
                    numsArray[i]=numsArray[i+1];
                    numsArray[i+1]=variableauxiliar;
                    //se crea un contador con un cambio
                    cantIntercambios++;
                }
            }
            //Si no hay intercambios, es que esta ordenado.
            if (cantIntercambios==0){
                ordenado=true;
            }
            //Inicializamos la variable de nuevo para que empiece a contar de nuevo
            cantIntercambios=0;
        }
       // String newArray;
        //newArray = String.valueOf(numsArray);
        
        
        
        String n;
        n= numeroBuscar.getText();
        
        int numInt = 0;
        numInt = Integer.parseInt(n);
        
        for(int i = 0; i < numsArray.length; i++) {
          if(numsArray[i] == numInt ){  
           pos=i; 
          }
            
        }    
        if(pos == -1){
        resul.setText("No se encontro el numero");
        }else{
        resul.setText("la posicion de " + n + " es: " + pos );
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private int[] valArray(String valores) {
        StringTokenizer tokenizer = new StringTokenizer(valores, ",");
        int newArray[] = new int[tokenizer.countTokens()];
        int i = 0;

        while (tokenizer.hasMoreTokens()) {
            newArray[i++] = Integer.parseInt(tokenizer.nextToken());
        }

        return newArray;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField numArreglo0;
    private javax.swing.JTextField numeroBuscar;
    private javax.swing.JTextField resul;
    // End of variables declaration//GEN-END:variables
}
